/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lottoapp;

import org.junit.Test;

import lottoapp.App;

import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void appHasALogger() {
        App classUnderTest = new App();
        assertNotNull("app should have a logger", classUnderTest.LOGGER);
    }
}
